receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp_grpc/tempo:
    endpoint: "192.168.50.10:4317"
    tls:
      insecure: true
  otlp_http/loki:
    endpoint: "http://192.168.50.10:3100/otlp"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/loki]